# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '03A0693A10A90A9AEFE552365EC256F4'

_lr_action_items = {'COLON': ([9, 10, ], [12, 13, ]), 'RIGHT_BRACE': (
    [11, 14, 15, 16, 18, 21, 25, 26, 27, 28, ], [15, -7, -10, 15, 15, -8, -9, -12, -13, -11, ]),
                    'LEFT_BRACE': ([7, ], [11, ]), 'ID': (
        [1, 6, 11, 14, 15, 16, 17, 18, 21, 25, 26, 27, 28, ],
        [7, 10, 17, -7, -10, 17, 24, 17, -8, -9, -12, -13, -11, ]),
                    'PACKAGE_ID': ([6, ], [9, ]), 'FIELD_DELIMITER': ([22, 23, 24, ], [26, 27, 28, ]), 'MESSAGE': (
        [0, 3, 11, 12, 13, 14, 15, 16, 17, 18, 21, 25, 26, 27, 28, ],
        [1, 1, 1, 1, 1, -7, -10, 1, 22, 1, -8, -9, -12, -13, -11, ]),
                    '$end': ([2, 3, 4, 5, 8, 14, 15, 19, 20, 21, 25, ], [-2, -5, 0, -1, -6, -7, -10, -4, -3, -8, -9, ]),
                    'PACKAGE': ([0, 17, ], [6, 23, ]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_action:  _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'message_contents': ([11, 16, 18, ], [14, 21, 25, ]),
                  'messages': ([0, 3, 12, 13, ], [2, 8, 19, 20, ]),
                  'nested_message': ([0, 3, 11, 12, 13, 16, 18, ], [3, 3, 16, 3, 3, 16, 16, ]), 'start': ([0, ], [4, ]),
                  'package': ([0, ], [5, ]), 'field': ([11, 16, 18, ], [18, 18, 18, ]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_goto: _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> start", "S'", 1, None, None, None),
    ('start -> package', 'start', 1, 'p_root', 'proto_parser.py', 11),
    ('start -> messages', 'start', 1, 'p_root', 'proto_parser.py', 12),
    ('package -> PACKAGE ID COLON messages', 'package', 4, 'p_package', 'proto_parser.py', 17),
    ('package -> PACKAGE PACKAGE_ID COLON messages', 'package', 4, 'p_package', 'proto_parser.py', 18),
    ('messages -> nested_message', 'messages', 1, 'p_messages', 'proto_parser.py', 23),
    ('messages -> nested_message messages', 'messages', 2, 'p_messages', 'proto_parser.py', 24),
    ('nested_message -> MESSAGE ID LEFT_BRACE message_contents', 'nested_message', 4, 'p_nested_message',
     'proto_parser.py', 36),
    ('message_contents -> nested_message message_contents', 'message_contents', 2, 'p_message_contents',
     'proto_parser.py', 47),
    ('message_contents -> field message_contents', 'message_contents', 2, 'p_message_contents', 'proto_parser.py', 48),
    ('message_contents -> RIGHT_BRACE', 'message_contents', 1, 'p_message_contents', 'proto_parser.py', 49),
    ('field -> ID ID FIELD_DELIMITER', 'field', 3, 'p_field', 'proto_parser.py', 67),
    ('field -> ID MESSAGE FIELD_DELIMITER', 'field', 3, 'p_field', 'proto_parser.py', 68),
    ('field -> ID PACKAGE FIELD_DELIMITER', 'field', 3, 'p_field', 'proto_parser.py', 69),
]
